---
# Example Github Workflow file to run Terraform Check action
name: Terraform Checks

on: [push, pull_request] # yamllint disable-line rule:truthy

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - name: Run Terraform Action from oak-terraform-actions
        # Update the commit SHA (and version comment) to the latest release before using:
        #   gh api repos/oaknational/oak-terraform-actions/commits/vX.Y.Z --jq .sha
        uses: oaknational/oak-terraform-actions/actions/terraform-checks@a1fe3aea1efa31ee5d29e387d584c006a2d33bcc # v1.13.1
